# Generated by Django 5.0.7 on 2024-07-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='shift_end',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='shift_start',
        ),
    ]
