# Generated by Django 5.0.7 on 2024-07-26 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_volunteer_shift_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='authentication.event'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('organizer', 'Oraganizer')], default='student', max_length=50),
        ),
    ]
