# Generated by Django 5.0.7 on 2024-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_event_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('not_say', 'Prefer not to say')], max_length=50, null=True),
        ),
    ]
